### ISSUE TITLE
Outdated docker image

### ISSUE THREAD

**Issue by Reyzorcat** [vultr/cert-manager-webhook-vultr#137]
Hello.

Currently the latest version of [cert-manager-webhook-vultr](https://github.com/vultr/cert-manager-webhook-vultr/releases/tag/helm-v0.4.1) uses old [docker image v0.3.1](https://github.com/vultr/cert-manager-webhook-vultr/blob/63236ae3a94ba875fff53b03a0b3e67896709dd4/deploy/cert-manager-webhook-vultr/values.yaml#L19), which uses a deprecated API:
`W1201 11:43:04.166441 1 warnings.go:70] flowcontrol.apiserver.k8s.io/v1beta2 FlowSchema is deprecated in v1.26+, unavailable in v1.29+; use flowcontrol.apiserver.k8s.io/v1beta3 FlowSchema`
`W1201 11:46:37.130000 1 warnings.go:70] flowcontrol.apiserver.k8s.io/v1beta2 PriorityLevelConfiguration is deprecated in v1.26+, unavailable in v1.29+; use flowcontrol.apiserver.k8s.io/v1beta3 PriorityLevelConfiguration`
Could you please update docker image?

**Comment by happytreees** [comment]
Hello,

The image you are referring to is the application release version of the Vultr cm webhook:
https://github.com/vultr/cert-manager-webhook-vultr/releases/tag/v0.3.1

This image is the most up-to-date and we do not use the API `flowcontrol.apiserver.k8s.io/v1beta2` anywhere within the webhook. These warnings are likely coming from an API being used by cert-manager. Can you share what version of cert-manager you have installed in the cluster?

**Comment by Reyzorcat** [comment]
Hello. We solved our problem by building our own image and replacing it in values.yaml
```
FROM golang:1.20-alpine AS repo

RUN apk add --no-cache git
WORKDIR /repo
RUN git clone -b helm-v0.4.1 https://github.com/vultr/cert-manager-webhook-vultr.git && \
    rm -rf ./cert-manager-webhook-vultr/vendor && \
    rm -rf ./cert-manager-webhook-vultr/go.sum

FROM golang:1.20-alpine AS build

WORKDIR /workspace

COPY --from=repo /repo/cert-manager-webhook-vultr/ .

RUN sed -i -e 's/go 1.19/go 1.20/g; s/cert-manager v1.10.1/cert-manager v1.12.10/g; /opentelemetry/d' go.mod && \
    sed -i -e 's/test\/acme\/dns/test\/acme/g' main_test.go
RUN go mod download
RUN go mod tidy
RUN go mod vendor

RUN CGO_ENABLED=0 go build -trimpath -o webhook -ldflags '-w -extldflags "-static"' .

FROM alpine:3.15

RUN apk add --no-cache ca-certificates

COPY --from=build /workspace/webhook /usr/local/bin/webhook

ENTRYPOINT ["webhook"]
```
