### ISSUE TITLE
Renewal of Certificate?

### ISSUE THREAD

**Issue by tzarger** [vultr/cert-manager-webhook-vultr#68]
Hello, not sure if I did something wrong, it seems that the certificate was not auto renewed. Is there something I can turn on or set to get this cert manager to auto-renew the certificate when the time is appropriate?

**Comment by happytreees** [comment]
@tzarger you do not need to specify any certain arguments to enable auto-renew as that aspect is handled by cert-manager itself. The webhook is simply a method for cert-manager to create the appropriate DNS records. 

Are you seeing any renewal attempts for the certificate? You should be able to see that with this command:
```
kubectl get certificaterequest -A
```

**Comment by tzarger** [comment]
Hi @happytreees this is what the command outputs, notice age of 111d

```
cert-manager   cert-manager-webhook-vultr-ca-9v6rh            True                True    cert-manager-webhook-vultr-selfsign   system:serviceaccount:cert-manager:cert-manager   111d
cert-manager   cert-manager-webhook-vultr-webhook-tls-jh4nf   True                True    cert-manager-webhook-vultr-ca         system:serviceaccount:cert-manager:cert-manager   111d
default        prod-mmgm-com-8kh65                            True                True    letsencrypt-prod                      system:serviceaccount:cert-manager:cert-manager   111d
```
